version: '3'

services:

  mysql-biodata:
    image: mysql:8.0
    container_name: mysql-biodata
    ports:
      - "3308:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: PasswordManager
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    networks:
      - my-external-network
      # - mysql-replication-network
    volumes:
      - ./db-data/mysql-biodata/:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --server-id=2 --log-bin=mysql-bin

networks:
  my-external-network:
    external: true